export const menu = [
  { id: 1, item: "Special Protein Shake", price: 400, isAvailable: true },
  { id: 2, item: "Mix Fruit Shake", price: 150, isAvailable: true },
  { id: 3, item: "Chocolate Shake", price: 150, isAvailable: false },
  { id: 4, item: "Chocolate Coconut Shake", price: 150, isAvailable: true },
  { id: 5, item: "Oreo Shake", price: 150, isAvailable: true },
  { id: 6, item: "Milk Bottle", price: 120, isAvailable: false },
  { id: 7, item: "Lassi", price: 140, isAvailable: true },
  { id: 8, item: "Pakola Milk", price: 100, isAvailable: true },
  { id: 9, item: "Sting Milk", price: 160, isAvailable: true },
  { id: 10, item: "Slice Milk", price: 160, isAvailable: true },
  { id: 11, item: "7up Milk", price: 160, isAvailable: true },
  { id: 12, item: "Rooh Afza Milk", price: 100, isAvailable: true },
  { id: 13, item: "Injeer Milkshake", price: 200, isAvailable: false },
  { id: 14, item: "Khajoor Milkshake", price: 180, isAvailable: true },
  { id: 15, item: "Banana Milkshake", price: 120, isAvailable: true },
  { id: 16, item: "Mango Shake", price: 150, isAvailable: true },
  { id: 17, item: "Cheeko Shake", price: 150, isAvailable: false },
  { id: 18, item: "Angoor Shake", price: 150, isAvailable: true },
  { id: 19, item: "Amlok Shake", price: 150, isAvailable: true },
  { id: 20, item: "Strawberry Shake", price: 150, isAvailable: false },
  { id: 21, item: "Mango Lassi", price: 160, isAvailable: true },
];
