export const menu = [
  { id: 1, item: "Special protein shake", price: 400, isAvailable: true },
  { id: 2, item: "Mix fruit shake", price: 150, isAvailable: true },
  { id: 3, item: "Chocolate shake", price: 150, isAvailable: false },
  { id: 4, item: "Chocolate coconut shake", price: 150, isAvailable: true },
  { id: 5, item: "Oreo shake", price: 150, isAvailable: true },
  { id: 6, item: "Milk bottle", price: 120, isAvailable: false },
  { id: 7, item: "Lassi", price: 120, isAvailable: true },
  { id: 8, item: "Pakola milk", price: 150, isAvailable: true },
  { id: 9, item: "Sting milk", price: 160, isAvailable: true },
  { id: 10, item: "Slice milk", price: 160, isAvailable: true },
  { id: 11, item: "7up milk", price: 160, isAvailable: true },
  { id: 12, item: "Rooh afza milk", price: 100, isAvailable: true },
  { id: 13, item: "Injeer milkshake", price: 200, isAvailable: false },
  { id: 14, item: "Khajoor milkshake", price: 180, isAvailable: true },
  { id: 15, item: "Banana milkshake", price: 120, isAvailable: true },
  { id: 16, item: "Mango shake", price: 150, isAvailable: true },
  { id: 17, item: "Cheeko shake", price: 150, isAvailable: false },
  { id: 18, item: "Angoor shake", price: 150, isAvailable: true },
  { id: 19, item: "Amlok shake", price: 150, isAvailable: true },
  { id: 20, item: "Strawberry shake", price: 150, isAvailable: false },
  { id: 21, item: "Mango lassi", price: 150, isAvailable: true },
];
